### ISSUE TITLE
Strange icon

### ISSUE THREAD

**Issue by 1Cedric1** [Travelbacon/MMM-TomTomTrafficIncidents#10]
Dear @Travelbacon ,
thank you first for your great module! it's a pleasure to see it running well.
Do you maybe know what the red icon on the attached printscreen means?

![IMG_20230416_135327_HDR (1)](https://user-images.githubusercontent.com/61581150/233762952-743eec90-35f1-4322-8e80-64d581419236.jpg)

It appeared after a while and keeps staying there.
Thank you in advance for your reply.
Kind regards,
Cédric

**Comment by Travelbacon** [comment]
Thanks for the compliment.

That is strange. I have no idea what it can be. What does the console writes? I personnaly enable the webserver option for the Magic Mirror so that I can read the console log output in the browser.

**Comment by 1Cedric1** [comment]
Thank you for your response @Travelbacon .

Surprising is, that this icone hasn't appeared anymore for 2 days, and has been replaced with a "route number".

So, even if we don't understand why, we can consider it issue to be closed.

Thank you anyway for your previous response and interest, and all the best so you.

**Comment by Travelbacon** [comment]
It could be an issue at TomTom site. After all, the icons are derived from them.
I think it is also time to update this module again. Hopefully with the option to have zoom levels better implemented.
