### ISSUE TITLE
wierd...

### ISSUE THREAD

**Issue by Alextheduke81** [Travelbacon/MMM-TomTomTrafficIncidents#2]
...modul works on iphone- and laptop-browser (full-hd and above), but not on display (1680x1050 resolution) that is directly attached to my raspberry.
modul also loaded, but i can't see the map. i've tried many different sizes of the map - but no change.

**Comment by Travelbacon** [comment]
That’s strange.
What are the settings and what does the debug of electron say?

**Comment by Alextheduke81** [comment]
{	
			module: "MMM-TomTomTrafficIncidents",
			position: "top_center",
			config: {
				key: "XXXXXXXXXXXXXXXXXXXXX",
				lng:  11.2377946,
				lat:  48.3006119,
				zoom: 10,
				height: "200px",
				width: "320px"
				}
		},

how do i debug?

**Comment by Travelbacon** [comment]
Pleas take a look at the forum for how to trouble shoot: https://forum.magicmirror.builders/topic/86/how-to-troubleshoot
