### ISSUE TITLE
Cannot read property 'hardwareConcurrency' of MMM-TomTomTrafficIncidents

### ISSUE THREAD

**Issue by robertybob** [Travelbacon/MMM-TomTomTrafficIncidents#3]
Hey. When I try to get this to work, in this case using your example config and my TomTom key, nothing loads on the Mirror. 
When I press CTRL+SHIFT+I to get to the Chromium debugger, this is what is says:

> Uncaught TypeError: Cannot read property 'hardwareConcurrency' of MMM-TomTomTrafficIncidents
>     undefined
>     at maps-web.min.js:1
>     at n (maps-web.min.js:1)
>     at n (maps-web.min.js:1)
>     at Object.<anonymous> (maps-web.min.js:1)
>     at r (maps-web.min.js:1)
>     at Object.<anonymous> (maps-web.min.js:1)
>     at r (maps-web.min.js:1)
>     at Object.<anonymous> (maps-web.min.js:1)
>     at r (maps-web.min.js:1)
>     at maps-web.min.js:1

> MMM-TomTomTrafficIncidents.js:69 Uncaught ReferenceError: tt is not defined
>     at HTMLScriptElement.script.onload (MMM-TomTomTrafficIn

When I view my MM through Firefox on my laptop, this is from the debugger:

> Source map error: Error: request failed with status 404
> Resource URL: http://192.xxx.x.xxx:8080/modules/MMM-TomTomTrafficIncidents/tomtom-international-web-sdk-maps/maps-web.min.js
> Source Map URL: maps-web.min.js.map

This is my config:

```
	{	
		module: "MMM-TomTomTrafficIncidents",
		position: "bottom_center",
		config: {
			key: 'thekey',
			lng: 0.667770,
			lat:  51.351990,
			zoom: 11,
			height: "500px",
			width: "800px"
		}
	},
```
Is there something I'm doing wrong?

**Comment by Travelbacon** [comment]
Please check if you can make a working example from TomTom's tutorial: https://developer.tomtom.com/maps-sdk-web-js/functional-examples

That will give you insight where it goes wrong.

**Comment by robertybob** [comment]
> 
> 
> Please check if you can make a working example from TomTom's tutorial: https://developer.tomtom.com/maps-sdk-web-js/functional-examples
> 
> That will give you insight where it goes wrong.

Apologies, that's not very helpful to me as I'm not very knowledgable about Javascript or coding in general. All I have changed from the example used in the README is my API Key and the lat & lng, so I can't see why it shouldn't work

**Comment by robertybob** [comment]
I have undertaken a completely new MagicMirror installation and after installing this module I now get these errors instead:  
  

>  Uncaught TypeError: self.navigator is undefined
>     n http://192.168.1.91:8080/modules/MMM-TomTomTrafficIncidents/tomtom-international-web-sdk-maps/maps-web.min.js:1
>     n http://192.168.1.91:8080/modules/MMM-TomTomTrafficIncidents/tomtom-international-web-sdk-maps/maps-web.min.js:1
>     n http://192.168.1.91:8080/modules/MMM-TomTomTrafficIncidents/tomtom-international-web-sdk-maps/maps-web.min.js:1
>     <anonymous> http://192.168.1.91:8080/modules/MMM-TomTomTrafficIncidents/tomtom-international-web-sdk-maps/maps-web.min.js:1
>     r http://192.168.1.91:8080/modules/MMM-TomTomTrafficIncidents/tomtom-international-web-sdk-maps/maps-web.min.js:1
>     <anonymous> http://192.168.1.91:8080/modules/MMM-TomTomTrafficIncidents/tomtom-international-web-sdk-maps/maps-web.min.js:1
>     r http://192.168.1.91:8080/modules/MMM-TomTomTrafficIncidents/tomtom-international-web-sdk-maps/maps-web.min.js:1
>     <anonymous> http://192.168.1.91:8080/modules/MMM-TomTomTrafficIncidents/tomtom-international-web-sdk-maps/maps-web.min.js:1
>     r http://192.168.1.91:8080/modules/MMM-TomTomTrafficIncidents/tomtom-international-web-sdk-maps/maps-web.min.js:1
>     <anonymous> http://192.168.1.91:8080/modules/MMM-TomTomTrafficIncidents/tomtom-international-web-sdk-maps/maps-web.min.js:1
>     <anonymous> http://192.168.1.91:8080/modules/MMM-TomTomTrafficIncidents/tomtom-international-web-sdk-maps/maps-web.min.js:1
> maps-web.min.js:1:25042
> Uncaught ReferenceError: tt is not defined
>     onload http://192.168.1.91:8080/modules/MMM-TomTomTrafficIncidents//MMM-TomTomTrafficIncidents.js:69
>     getDom http://192.168.1.91:8080/modules/MMM-TomTomTrafficIncidents//MMM-TomTomTrafficIncidents.js:68
>     updateDom http://192.168.1.91:8080/js/main.js:111
>     updateDom http://192.168.1.91:8080/js/main.js:110
>     createDomObjects http://192.168.1.91:8080/js/main.js:52
>     createDomObjects http://192.168.1.91:8080/js/main.js:21
>     modulesStarted http://192.168.1.91:8080/js/main.js:499
>     startModules http://192.168.1.91:8080/js/loader.js:56
>     loadNextModule http://192.168.1.91:8080/js/loader.js:38
>     onerror http://192.168.1.91:8080/js/loader.js:207
>     loadFile http://192.168.1.91:8080/js/loader.js:204
>     loadNextModule http://192.168.1.91:8080/js/loader.js:36
>     loadNextModule http://192.168.1.91:8080/js/loader.js:29
>     afterLoad http://192.168.1.91:8080/js/loader.js:122
>     bootstrapModule http://192.168.1.91:8080/js/loader.js:158
>     loadTranslations http://192.168.1.91:8080/js/module.js:333
>     bootstrapModule http://192.168.1.91:8080/js/loader.js:155
>     loadNextDependency http://192.168.1.91:8080/js/module.js:296
>     loadNextDependency http://192.168.1.91:8080/js/module.js:293
>     onload http://192.168.1.91:8080/js/loader.js:201
>     loadFile http://192.168.1.91:8080/js/loader.js:199
>     loadFile http://192.168.1.91:8080/js/loader.js:259
>     loadNextDependency http://192.168.1.91:8080/js/module.js:291
>     loadNextDependency http://192.168.1.91:8080/js/module.js:293
>     loadFile http://192.168.1.91:8080/js/loader.js:236
>     loadNextDependency http://192.168.1.91:8080/js/module.js:291
>     loadDependencies http://192.168.1.91:8080/js/module.js:300
>     loadStyles http://192.168.1.91:8080/js/module.js:266
>     bootstrapModule http://192.168.1.91:8080/js/loader.js:153
>     loadNextDependency http://192.168.1.91:8080/js/module.js:296
>     loadDependencies http://192.168.1.91:8080/js/module.js:300
>     loadScripts http://192.168.1.91:8080/js/module.js:275
>     bootstrapModule http://192.168.1.91:8080/js/loader.js:151
>     afterLoad http://192.168.1.91:8080/js/loader.js:121
>     loadModule http://192.168.1.91:8080/js/loader.js:134
>     onload http://192.168.1.91:8080/js/loader.js:181
>     loadFile http://192.168.1.91:8080/js/loader.js:179
>     loadModule http://192.168.1.91:8080/js/loader.js:132
>     loadNextModule http://192.168.1.91:8080/js/loader.js:27
>     loadNextModule http://192.168.1.91:8080/js/loader.js:29
>     afterLoad http://192.168.1.91:8080/js/loader.js:122
>     bootstrapModule http://192.168.1.91:8080/js/loader.js:158
>     loadTranslations http://192.168.1.91:8080/js/module.js:333
>     bootstrapModule http://192.168.1.91:8080/js/loader.js:155
>     loadNextDependency http://192.168.1.91:8080/js/module.js:296
>     loadNextDependency http://192.168.1.91:8080/js/module.js:293
>     onload http://192.168.1.91:8080/js/loader.js:201
>     loadFile http://192.168.1.91:8080/js/loader.js:199
>     loadFile http://192.168.1.91:8080/js/loader.js:259
>     loadNextDependency http://192.168.1.91:8080/js/module.js:291
>     loadNextDependency http://192.168.1.91:8080/js/module.js:293
>     onload http://192.168.1.91:8080/js/loader.js:201
>     loadFile http://192.168.1.91:8080/js/loader.js:199
>     loadFile http://192.168.1.91:8080/js/loader.js:259
>     loadNextDependency http://192.168.1.91:8080/js/module.js:291
>     loadDependencies http://192.168.1.91:8080/js/module.js:300
>     loadStyles http://192.168.1.91:8080/js/module.js:266
>     bootstrapModule http://192.168.1.91:8080/js/loader.js:153
>     loadNextDependency http://192.168.1.91:8080/js/module.js:296
>     loadDependencies http://192.168.1.91:8080/js/module.js:300
>     loadScripts http://192.168.1.91:8080/js/module.js:275
>     bootstrapModule http://192.168.1.91:8080/js/loader.js:151
>     afterLoad http://192.168.1.91:8080/js/loader.js:121
>     loadModule http://192.168.1.91:8080/js/loader.js:134
>     onload http://192.168.1.91:8080/js/loader.js:181
>     loadFile http://192.168.1.91:8080/js/loader.js:179
> MMM-TomTomTrafficIncidents.js:69:4


> ​Source map error: Error: request failed with status 404
> Resource URL: http://192.168.1.91:8080/modules/MMM-TomTomTrafficIncidents/tomtom-international-web-sdk-maps/maps-web.min.js
> Source Map URL: maps-web.min.js.map

**Comment by swampy242001** [comment]
> Hey. When I try to get this to work, in this case using your example config and my TomTom key, nothing loads on the Mirror.
> When I press CTRL+SHIFT+I to get to the Chromium debugger, this is what is says:
> 
> > Uncaught TypeError: Cannot read property 'hardwareConcurrency' of MMM-TomTomTrafficIncidents
> > undefined
> > at maps-web.min.js:1
> > at n (maps-web.min.js:1)
> > at n (maps-web.min.js:1)
> > at Object. (maps-web.min.js:1)
> > at r (maps-web.min.js:1)
> > at Object. (maps-web.min.js:1)
> > at r (maps-web.min.js:1)
> > at Object. (maps-web.min.js:1)
> > at r (maps-web.min.js:1)
> > at maps-web.min.js:1
> 
> > MMM-TomTomTrafficIncidents.js:69 Uncaught ReferenceError: tt is not defined
> > at HTMLScriptElement.script.onload (MMM-TomTomTrafficIn
> 
> When I view my MM through Firefox on my laptop, this is from the debugger:
> 
> > Source map error: Error: request failed with status 404
> > Resource URL: http://192.xxx.x.xxx:8080/modules/MMM-TomTomTrafficIncidents/tomtom-international-web-sdk-maps/maps-web.min.js
> > Source Map URL: maps-web.min.js.map
> 
> This is my config:
> 
> ```
> 	{	
> 		module: "MMM-TomTomTrafficIncidents",
> 		position: "bottom_center",
> 		config: {
> 			key: 'api key,
> 			lng: 0.667770,
> 			lat:  51.351990,
> 			zoom: 11,
> 			height: "500px",
> 			width: "800px"
> 		}
> 	},
> ```
> 
> Is there something I'm doing wrong?

Hi,

I'm not the best at things like this. However i see you have the - missing on your lng.

lng: 0.667770

I think it may need to be lag: -0.667770 try this and see if it helps. May be something that simple.

**Comment by Travelbacon** [comment]
What hardware are you running the MM on?
Also, hide your API key. It was plainly written here. ;)

**Comment by Travelbacon** [comment]
I tested with your API key. It seems that you have to verify something in the developer site of tomtom.
This what I saw in the debug:
Object { status: 403, url: "https://api.tomtom.com/map/1/sprite/20.0.2-10/lite/sprite.json?key=yourkeykeepitsecret", name: "e", message: "Forbidden", stack: "" }

**Comment by robertybob** [comment]
> 
> 
> What hardware are you running the MM on?
> Also, hide your API key. It was plainly written here. ;)

Raspberry Pi 3b+  . Ah yes, I didn't think sharing my key would cause me any issues though haha. Thanks for editing my post :)

**Comment by robertybob** [comment]
> 
> 
> I tested with your API key. It seems that you have to verify something in the developer site of tomtom.
> This what I saw in the debug:
> Object { status: 403, url: "https://api.tomtom.com/map/1/sprite/20.0.2-10/lite/sprite.json?key=yourkeykeepitsecret", name: "e", message: "Forbidden", stack: "" }

Ah ok, according to https://developer.tomtom.com/search-api/search-api-documentation-search/nearby-search 


403 | Forbidden: Possible causes include:           

- Service requires SSL             
- Not authorized            
- Rate or volume limit exceeded          
- Unknown referer

Re: SSL; I'm viewing/setting up my MagicMirror by connecting to my Pi on a HTTP address, could it be that I need to change this to HTTPS?  
As for not being authorised, I've no idea what to do. I can't find anywhere that says I need to verify my account. In fact, I've created a brand new account and even that new API key results in the same error messages :(

**Comment by robertybob** [comment]
@Travelbacon I posted on their [forums](https://devforum.tomtom.com/t/object-status-403-name-e-message-forbidden-stack/1223) and the guy said  

> 404 means that the source map is not hosted with the app. You can download it and put it in the proper folder

Does that help at all?

**Comment by Travelbacon** [comment]
MM installation issue or user inactive (403)
