### ISSUE TITLE
Black screen 

### ISSUE THREAD

**Issue by r4zi3lrrr** [Travelbacon/MMM-TomTomTrafficIncidents#4]
Hi,

I’ve managed to install the Module but I’m getting just a black screen for the module.

Have I forgotten to install something?

![Capture](https://user-images.githubusercontent.com/38400294/97732090-eb1b8800-1acd-11eb-9273-6a47f8e5bf56.JPG)

Code for my config.js below:

module: “MMM-TomTomTrafficIncidents”,
position: “center”,
config: {
key: “”,
lng: -123.1139529,
lat: 49.2608724,
zoom: 11,
height: “500px”,
width: “800px”

Thank you.

**Comment by Travelbacon** [comment]
Did you check the debug log? There should be more information why the map is not being loaded.
Perhaps you will find the reason and solution.Otherwise copy paste the log here.

**Comment by r4zi3lrrr** [comment]
Please see below:

loader.js:182 Load script: modules/default/alert/modernizr.custom.js
/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:128 Electron Security Warning (Insecure Resources) This renderer process loads resources using insecure protocols. This exposes users of this app to unnecessary security risks. Consider loading the following resources over HTTPS or FTPS. 
- http://localhost:8080/css/main.css
- http://localhost:8080/fonts/roboto.css
- http://localhost:8080/socket.io/socket.io.js
- http://localhost:8080/vendor/node_modules/nunjucks/browser/nunjucks.min.js
- http://localhost:8080/js/defaults.js
- http://localhost:8080/config/config.js
- http://localhost:8080/vendor/vendor.js
- http://localhost:8080/modules/default/defaultmodules.js
- http://localhost:8080/js/logger.js
- http://localhost:8080/translations/translations.js
- http://localhost:8080/js/translator.js
- http://localhost:8080/js/class.js
- http://localhost:8080/js/module.js
- http://localhost:8080/js/loader.js
- http://localhost:8080/js/socketclient.js
- http://localhost:8080/js/main.js
- http://localhost:8080/fonts/node_modules/roboto-fontface/fonts/roboto-condensed/Roboto-Condensed-Regular.woff2
- http://localhost:8080/translations/en.json
- http://localhost:8080/translations/en.json
- http://localhost:8080/modules/default/alert//alert.js
- http://localhost:8080/modules/default/alert/classie.js
- http://localhost:8080/modules/default/alert/modernizr.custom.js
- http://localhost:8080/modules/default/alert/notificationFx.js
- http://localhost:8080/modules/default/alert/ns-default.css

For more information and help, consult https://electronjs.org/docs/tutorial/security.
This warning will not show up once the app is packaged.
warnAboutInsecureResources @ /home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:128
loader.js:182 Load script: modules/MMM-TomTomTrafficIncidents//MMM-TomTomTrafficIncidents.js
module.js:477 Module registered: MMM-TomTomTrafficIncidents
loader.js:152 Bootstrapping module: MMM-TomTomTrafficIncidents
loader.js:157 Scripts loaded for: MMM-TomTomTrafficIncidents
loader.js:197 Load stylesheet: modules/MMM-TomTomTrafficIncidents/tomtom-international-web-sdk-maps/maps.css
loader.js:197 Load stylesheet: modules/MMM-TomTomTrafficIncidents/tomtom-international-web-sdk-maps/traffic-incidents.css
loader.js:159 Styles loaded for: MMM-TomTomTrafficIncidents
loader.js:161 Translations loaded for: MMM-TomTomTrafficIncidents
loader.js:197 Load stylesheet: css/custom.css
MMM-TomTomTrafficIncidents.js:35 Starting module: MMM-TomTomTrafficIncidents
MMM-TomTomTrafficIncidents.js:44 MMM-TomTomTrafficIncidents: Using JS & CSS from local source.
module.js:156 MMM-TomTomTrafficIncidents received a system notification: ALL_MODULES_STARTED
module.js:156 MMM-TomTomTrafficIncidents received a system notification: MODULE_DOM_CREATED
module.js:156 MMM-TomTomTrafficIncidents received a system notification: DOM_OBJECTS_CREATED
module.js:154 MMM-TomTomTrafficIncidents received a module notification: CURRENTWEATHER_DATA from sender: currentweather
maps-web.min.js:1 Error: Failed to initialize WebGL
    at A._setupPainter (maps-web.min.js:1)
    at new A (maps-web.min.js:1)
    at e.mapboxMapFactory (maps-web.min.js:1)
    at t.createMap (maps-web.min.js:1)
    at new map (maps-web.min.js:1)
    at HTMLScriptElement.script.onload (MMM-TomTomTrafficIncidents.js:70)
wt.fire @ maps-web.min.js:1
maps-web.min.js:1 Uncaught Error: Failed to initialize WebGL.
    at new A (maps-web.min.js:1)
    at e.mapboxMapFactory (maps-web.min.js:1)
    at t.createMap (maps-web.min.js:1)
    at new map (maps-web.min.js:1)
    at HTMLScriptElement.script.onload (MMM-TomTomTrafficIncidents.js:70)
module.js:154 MMM-TomTomTrafficIncidents received a module notification: CALENDAR_EVENTS from sender: calendar

**Comment by r4zi3lrrr** [comment]
Managed to fix it myself using the below:

Console: sudo raspi-config Under "7 Advanced Options" / "A7 GL Driver" pick "G2 GL (Fake KMS)"

Desktop: Preferences / Add Remove Software search for "Chrome" and pick "WebDriver driver for the Chromium Browser", click "OK"

**Comment by abdelhadj** [comment]
Hello,
i am getting black screen, my config is simple, i tried also to swipe lon and lat
how can i acces the debu log?
Thank you for your help.
btw the other module TomTom works fine
		{
		disabled:false,	
		module: "MMM-TomTomTrafficIncidents",
		position: "top_center",
			config: {
				key: "xxx",
				lng: 48.926916,
				lat:  2.1868998,
				traffic: "relative",
				zoom: 11,
				height: "200px",
				width: "800px",
				lang:"fr"
			}
		
		},

**Comment by Travelbacon** [comment]
The debug is on Magic Mirror level. Please see the magic mirror documentation.
Because TomTom is javascript, you can see the logs when you open the debug window of your browser or start the Magic Mirror with the debug option.
What I commonly do to test is activate Magic Mirror that it can be accessed via a browser, so that I have more control over it. I start Magic Mirror as a server on the Pi and allow remote access in the config. Then I can use my laptop to see what is going on in the debug window.
https://docs.magicmirror.builders/getting-started/configuration.html#raspberry-specific

**Comment by Travelbacon** [comment]
Did you check https://forum.magicmirror.builders/topic/13938/black-screen/7 as well?

**Comment by abdelhadj** [comment]
hello, actually nothing appear on my screen, i don't have the frame as shown in the first picture.
I tried fake KMS also
below  what i got on the console from developer's part :
Load script:modules/MMM-TomTomTrafficIncidents/MMM-TomTomTrafficIncidents.js
module.js:516 Module registered: MMM-TomTomTrafficIncidents
loader.js:157 Bootstrapping module: MMM-TomTomTrafficIncidents
loader.js:162 Scripts loaded for: MMM-TomTomTrafficIncidents
loader.js:204 Load stylesheet: https://api.tomtom.com/maps-sdk-for-web/cdn/6.x/6.12.0/maps/maps.css
loader.js:164 Styles loaded for: MMM-TomTomTrafficIncidents
loader.js:166 Translations loaded for: MMM-TomTomTrafficIncidents
MMM-TomTomTrafficIncidents.js:30 Starting module: MMM-TomTomTrafficIncidents
MMM-TomTomTrafficIncidents.js:36 MMM-TomTomTrafficIncidents: Using JS from https://api.tomtom.com/maps-sdk-for-web/cdn/6.x/6.12.0
mapbox-gl.js:35 Uncaught TypeError: Cannot read property 'getElementById' of undefined
    at new i (mapbox-gl.js:35)
    at aA (mapFactory.js:1528)
    at BA.createMap (mapConfigurer.js:67)
    at Object.map (index.js:59)
    at HTMLScriptElement.script.onload (MMM-TomTomTrafficIncidents.js:64)
module.js:206 MMM-TomTomTrafficIncidents is resumed.
3
module.js:206 MMM-TomTomTrafficIncidents is resumed.
module.js:199 MMM-TomTomTrafficIncidents is suspended.
﻿
​

**Comment by ncardillo** [comment]
Am I missing a step? Does this module not need to be installed somehow before adding it to the config?

**Comment by Travelbacon** [comment]
It doesn't need any installation. Just an Tomtom API key.

**Comment by Jeffodilo** [comment]
Hello,

After many trials, with the [version raspbian Raspberry Pi OS (Legacy)](https://www.raspberrypi.com/news/new-old-functionality-with-raspberry-pi-os-legacy/) and the open GL fake KMS in the raspi-config (6 Advanced options / A2 GL driver / G2 GL Fake KMS), that's work.

**Comment by Travelbacon** [comment]
> Hello,
> 
> After many trials, with the [version raspbian Raspberry Pi OS (Legacy)](https://www.raspberrypi.com/news/new-old-functionality-with-raspberry-pi-os-legacy/) and the open GL fake KMS in the raspi-config (6 Advanced options / A2 GL driver / G2 GL Fake KMS), that's work.

Thank you so much for solving this!
