### ISSUE TITLE
t.window.document is undefined

### ISSUE THREAD

**Issue by robertybob** [Travelbacon/MMM-TomTomTrafficIncidents#7]
Hi. I can't get this module to display anything on my Magic Mirror, when I look at the console it shows the following error:

> Uncaught TypeError: t.window.document is undefined
>     i mapbox-gl.js:35
>     aA mapFactory.js:1528
>     BA mapConfigurer.js:67
>     map index.js:59
>     onload MMM-TomTomTrafficIncidents.js:64

I am trying to set it up using a brand new MM image that I created yesterday. For reference, my config is as follows:
```
		{
			module: "MMM-TomTomTrafficIncidents",
			position: "top_center",
			config: {
				key: REMOVE YOUR KEY,
				lng: 0.631025047302246,
				lat: 50.348021066230956,
				zoom: 11,
				height: "900px",
				width: "800px"
			}
		},
```

I even tried your default example with my API key and that didn't work, and I got an even longer error message

> Uncaught TypeError: t.window.document is undefined
>     i mapbox-gl.js:35
>     aA mapFactory.js:1528
>     BA mapConfigurer.js:67
>     map index.js:59
>     onload MMM-TomTomTrafficIncidents.js:64
>     getDom MMM-TomTomTrafficIncidents.js:62
>     updateDom main.js:114
>     updateDom main.js:113
>     createDomObjects main.js:53
>     createDomObjects main.js:20
>     modulesStarted main.js:510
>     startModules loader.js:56
>     loadNextModule loader.js:38
>     onerror loader.js:217
>     loadFile loader.js:214
>     loadNextModule loader.js:36
>     loadNextModule loader.js:29
>     afterLoad loader.js:132
>     bootstrapModule loader.js:168
>     loadTranslations module.js:322
>     bootstrapModule loader.js:165
>     loadNextDependency module.js:302
>     loadNextDependency module.js:299
>     onload loader.js:211
>     loadFile loader.js:209
>     loadFile loader.js:269
>     loadNextDependency module.js:297
>     loadDependencies module.js:306
>     loadStyles module.js:272
>     bootstrapModule loader.js:163
>     loadNextDependency module.js:302
>     loadNextDependency module.js:299
>     loadFile loader.js:246
>     loadNextDependency module.js:297
>     loadDependencies module.js:306
>     loadScripts module.js:281
>     bootstrapModule loader.js:161
>     afterLoad loader.js:131
>     loadModule loader.js:144
>     onload loader.js:191
>     loadFile loader.js:189
>     loadModule loader.js:142
>     loadNextModule loader.js:27
>     loadNextModule loader.js:29
>     afterLoad loader.js:132
>     bootstrapModule loader.js:168
>     loadTranslations module.js:322
>     bootstrapModule loader.js:165
>     loadNextDependency module.js:302
>     loadNextDependency module.js:299
>     loadFile loader.js:246
>     loadNextDependency module.js:297
>     loadNextDependency module.js:299
>     loadFile loader.js:246
>     loadNextDependency module.js:297
>     loadNextDependency module.js:299
>     loadFile loader.js:246
>     loadNextDependency module.js:297
>     loadDependencies module.js:306
>     loadStyles module.js:272
>     bootstrapModule loader.js:163
>     loadNextDependency module.js:302
>     loadNextDependency module.js:299
>     loadFile loader.js:246
>     loadNextDependency module.js:297
>     loadNextDependency module.js:299
>     loadFile loader.js:246
>     loadNextDependency module.js:297
>     loadNextDependency module.js:299
>     loadFile loader.js:246
> mapbox-gl.js:35:315631
>     i mapbox-gl.js:35
>     aA mapFactory.js:1528
>     BA mapConfigurer.js:67
>     map index.js:59
>     onload MMM-TomTomTrafficIncidents.js:64
>     (Async: EventHandlerNonNull)
>     getDom MMM-TomTomTrafficIncidents.js:62
>     updateDom main.js:114
>     updateDom main.js:113
>     createDomObjects main.js:53
>     forEach self-hosted:206
>     createDomObjects main.js:20
>     modulesStarted main.js:510
>     startModules loader.js:56
>     loadNextModule loader.js:38
>     onerror loader.js:217
>     (Async: EventHandlerNonNull)
>     loadFile loader.js:214
>     loadNextModule loader.js:36
>     loadNextModule loader.js:29
>     afterLoad loader.js:132
>     bootstrapModule loader.js:168
>     loadTranslations module.js:322
>     bootstrapModule loader.js:165
>     loadNextDependency module.js:302
>     loadNextDependency module.js:299
>     onload loader.js:211
>     (Async: EventHandlerNonNull)
>     loadFile loader.js:209
>     loadFile loader.js:269
>     loadNextDependency module.js:297
>     loadDependencies module.js:306
>     loadStyles module.js:272
>     bootstrapModule loader.js:163
>     loadNextDependency module.js:302
>     loadNextDependency module.js:299
>     loadFile loader.js:246
>     loadNextDependency module.js:297
>     loadDependencies module.js:306
>     loadScripts module.js:281
>     bootstrapModule loader.js:161
>     afterLoad loader.js:131
>     loadModule loader.js:144
>     onload loader.js:191
>     (Async: EventHandlerNonNull)
>     loadFile loader.js:189
>     loadModule loader.js:142
>     loadNextModule loader.js:27
>     loadNextModule loader.js:29
>     afterLoad loader.js:132
>     bootstrapModule loader.js:168
>     loadTranslations module.js:322
>     bootstrapModule loader.js:165
>     loadNextDependency module.js:302
>     loadNextDependency module.js:299
>     loadFile loader.js:246
>     loadNextDependency module.js:297
>     loadNextDependency module.js:299
>     loadFile loader.js:246
>     loadNextDependency module.js:297
>     loadNextDependency module.js:299
>     loadFile loader.js:246
>     loadNextDependency module.js:297
>     loadDependencies module.js:306
>     loadStyles module.js:272
>     bootstrapModule loader.js:163
>     loadNextDependency module.js:302
>     loadNextDependency module.js:299
>     loadFile loader.js:246
>     loadNextDependency module.js:297
>     loadNextDependency module.js:299
>     loadFile loader.js:246
>     loadNextDependency module.js:297
>     loadNextDependency module.js:299
>     loadFile loader.js:246

Can you tell me where I'm going wrong? :)

**Comment by Travelbacon** [comment]
Which version did you download from this repository?  Is that the latest version?
P.s. removed your key from the post.

**Comment by robertybob** [comment]
I didn't realise I could download different versions lol. There are no installation instructions, but I presumed I just needed to use: 

`git clone https://github.com/Travelbacon/MMM-TomTomTrafficIncidents.git `

**Comment by Travelbacon** [comment]
The branch version. It could be that you're using an older version.
I have to look in to it.

**Comment by Travelbacon** [comment]
I added an  HTML file in the latest push. See if this is working as well.

**Comment by robertybob** [comment]
![image](https://user-images.githubusercontent.com/2610395/120549247-3fcc0c00-c3eb-11eb-95bb-80549fb66051.png)
I get this error and no map appears

**Comment by Travelbacon** [comment]
Fixed the HTML file by adding the cascade style sheet. Can you see if it works now for you as well?

**Comment by robertybob** [comment]
The good news is that the HTML file works perfectly, I have edited it and get a map (so my key isn't the issue at least lol)

I'm still, however, getting the same error message 

![image](https://user-images.githubusercontent.com/2610395/120827758-ad934780-c553-11eb-9d81-891475913c20.png)

**Comment by robertybob** [comment]
On an unreleated note, your example config throws up an error. Rather than:
```

width: "800px"
		}
	]
```

it should be

```
width: "800px"
		}
},
	]
```

**Comment by Travelbacon** [comment]
Thanks for pointing out the typo in the example.
Still strange, I know it works. Perhpaps it conflicts with another package. Could you test it in a config with only TomTom enabled?

**Comment by Travelbacon** [comment]
Module works for other devices and tested here on my MM. It must be a user setting.
